### ISSUE TITLE
Print preview and PDF download do not work

### ISSUE THREAD

**Issue by ElenaGallo** [GeoNode/geonode-mapstore-client#1118]
For both Layers and Maps the print preview is not visible and the printed PDF is not downloaded.

**How to Reproduce**
- See the steps in the gif below:

https://user-images.githubusercontent.com/56537133/181205971-8a681340-5bcd-40d2-aa23-e5b8bc8a9a3e.mov

**Comment by giohappy** [comment]
@DavidQuartz can you please check this? It's a really strange behaviour. it looks like on developmetn it does a request to a strange URL, instead of the usual create.json endpoint.

This is development:
![image](https://user-images.githubusercontent.com/571129/182342867-ec48d32a-7856-4df9-a3c8-0ffc99a9d57d.png)

This is master:
![image](https://user-images.githubusercontent.com/571129/182342887-dc4dbdfa-06b6-41e1-898b-ce89563caba4.png)

**Comment by afabiani** [comment]
@giohappy please make sure the on both `config.yml` and `.env -> GEOSERVER_OPTS` the `proxyBaseUrl` and/or `PRINT_BASE_URL` matches the public one: https://development.demo.geonode.org/geoserver/pdf

![image](https://user-images.githubusercontent.com/1278021/182595473-c0c1b3fe-0fa0-4a37-b5de-3a162db70b98.png)

**Comment by giohappy** [comment]
I suspect [this is the problem](https://github.com/GeoNode/geonode-project/blob/4.x/.env.sample#L108). The templated string wasn't converted when the .env file was generated...

**Comment by giohappy** [comment]
@ElenaGallo fixed. It was a configuration problem of the demo server. Please test again and close this in case it succeeds.

**Comment by ElenaGallo** [comment]
@giohappy test passed.
