### ISSUE TITLE
Some filters for Area of Interest not working

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1194]
@marthamareal commented on [Mon Sep 05 2022](https://github.com/GeoNode/geonode/issues/9953)

## Expected Behavior
All filters should display correct results when applied

## Actual Behavior
Some filters are not working eg
![b2](https://user-images.githubusercontent.com/20810749/188435224-ea894bb5-8028-4d33-945f-346ad07f7b84.png)

![b3](https://user-images.githubusercontent.com/20810749/188435231-12cfd399-845b-4323-b0d2-f773020d98da.png)

## Steps to Reproduce the Problem

  1. View a dataset with some data features eg https://master.demo.geonode.org/catalogue/#/dataset/2467
  2. Click on Filter from the menu, select the filter type as `Polygon` and `Geometry` as `Contains` or `Is contained`
  3. Draw a polygon containing some of the features. 
  4. Notice that all features will disappear

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by DavidQuartz** [comment]
@giohappy when using `Contains` the polygon drawn should full contain at least one full feature of the layer (without any edges outside of the polygon), otherwise none of the features will meet the condition of being fully contained inside the polygon.
In this example, the filter type is set to `Polygon` and geometric operation is `contains`, however, none  of the features are fully contained inside the polygon
>![Screenshot 2022-09-14 at 13 00 07](https://user-images.githubusercontent.com/42542676/190160963-1609a7f2-8041-43ea-b860-9ac8ed3e6123.png)
In this case, all the features will disappear when the filter is applied.

Further, with 'Is Contained', at least one feature should fully contain the polygon/circle. 
Example of fully contained polygon
>![Screenshot 2022-09-14 at 13 10 12](https://user-images.githubusercontent.com/42542676/190163255-d5c939a6-e23e-4748-9047-1b64390c63bc.png)
In this example, the polygon is contained in the bottom feature

Example of non-contained polygon
>![Screenshot 2022-09-14 at 13 08 10](https://user-images.githubusercontent.com/42542676/190163449-270ca58b-7128-40a6-a6a3-37906c51134f.png)
In this case, a more astute geometric operation would be `contains` as several features are fully contained in the polygon, but non of them fully contains the polygon.

**Comment by giohappy** [comment]
@DavidQuartz your explanation makes totally sense. No issue here @marthamareal
