### ISSUE TITLE
Style Editor will not allow editing saved style again

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#121]
@gannebamm commented on [Thu Apr 08 2021](https://github.com/GeoNode/geonode/issues/7265)

## Expected Behavior

After saving my style I will be able to edit it again to fix errors.

## Actual Behavior

The style will not load:

![grafik](https://user-images.githubusercontent.com/6172324/114061921-3a44c080-9897-11eb-95ea-e8f1e9b4d6be.png)

## Steps to Reproduce the Problem

  1. create new style from template (css)
  2. save style
  3. try to edit it again

## Specifications

  - GeoNode version: 3.2 (master.demo.geonode.org)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

---

@giohappy commented on [Fri Apr 09 2021](https://github.com/GeoNode/geonode/issues/7265#issuecomment-816507175)

@gannebamm we're going to make some tests with UTF-8 chars. We suspect this is connected to https://github.com/GeoNode/geonode/issues/7267.
I'm going to move both the issues to the mapstore client repo.

**Comment by allyoucanmap** [comment]
@gannebamm Did you create the style in the client and then edited in the editor of GeoServer?
cc: @giohappy
 
The name of the style seems the same of issue https://github.com/GeoNode/geonode-mapstore-client/issues/122 where some chars are not rendered in the legend so I'm wondering if the reason of this bug could be related to this because it seems the request are generating an error through the geonode proxy.

I tried to create a new style and use those chars äöü in the title but the proxy is not able to process the style.


![image](https://user-images.githubusercontent.com/19175505/114152807-fac1b700-991e-11eb-8822-c6aefc069671.png)

![image](https://user-images.githubusercontent.com/19175505/114153324-7facd080-991f-11eb-87ce-f41ab56a2e62.png)

**Comment by gannebamm** [comment]
@allyoucanmap I tested it again. Using an Style without special characters will work as expected. The loading error described above will only occur on having a legend label with non ascii characters like 'üöä'.

**Comment by allyoucanmap** [comment]
thanks @gannebamm
