### ISSUE TITLE
Some checkbox filter combinations fail

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1310]
No results returned with the following filters

![s](https://user-images.githubusercontent.com/20810749/202132472-be2936e2-8ae8-420d-8fe3-dba464ab22b6.png)

**Comment by giohappy** [comment]
@DavidQuartz the problem happens when the root Datasets is not selected.

Case 1 - Datasets not selected, the `OR` filter doesn't work as expected
![image](https://user-images.githubusercontent.com/571129/202213117-cbe6f927-dbd9-4b88-9121-147fe8c05a7b.png)

Case 2 - Dataset selected, the `OR` filter works as expected
![image](https://user-images.githubusercontent.com/571129/202213203-ff27dad1-f88c-4057-a5ad-ecfb71b02fa7.png)
