### ISSUE TITLE
Read user permissions on resource from GEONODE_CONFIG permissionsList 

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#146]
**NOTICE: ONLY for 2.1.x**

The permissions of a user on the current resource (layer, map, geostory) are available inside the `__GEONODE_CONFIG__.permissionsList` property. These will the permissions to use to drive the available actions for a resource.

For the moment the strings of intereset for the client that can be returned inside this property are:

view_resourcebase -> view the resource
download_resourcebase -> activate the export buttons
change_layer_data -> can edit layer data (only useful for vectors) .-> activate the edit on button for the featuregrid
change_layer_style -> can edit layer style -> activate the button to edit the layer's style
other permissions will be returned, and they will be used in the future versions of the client

These permissions will replace the current "canEdit, canDownload, etc." strings inside the client code.

**Comment by allyoucanmap** [comment]
@giohappy I think we cannot use the permissionsList inside a map or a layer page because we could have multiple layers inside the TOC and currently we are using the edit-check and style-check, I thought we could use the new API V2 to make the request but we have not information about the primary key of the resource from the CSW catalog or injected configuration.
Should we start to hide the download and feature grid based on the edit-check?

**Comment by giohappy** [comment]
As discussed in our call this issue is apparently already done, since you say that the cleitn already tries to read the `permissionsList` and, if not available, do a fallback to map resource info object.

The only thing I would do is to remove this fallback to ensure that we're not going to read the old values anymore.
