### ISSUE TITLE
Configure the client to request 512x512 tiles by default

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#215]
We want to increase the default 256x256 to 512x512.
@allyoucanmap I don't remember if this configuration is statically set js side or if it's passed inside the context.

**Comment by allyoucanmap** [comment]
@giohappy are we referring only to the layer or also the map pages?
The configuration for the maps and layers is included using 3 different sources:
- from CSW catalog
- from injected configuration
- from v2 or adapter api

@MuhweziDeo we should investigate if the tileSize property in the layer object should be configured client or server side

**Comment by MuhweziDeo** [comment]
> @giohappy are we referring only to the layer or also the map pages?
> The configuration for the maps and layers is included using 3 different sources:
> 
> * from CSW catalog
> * from injected configuration
> * from v2 or adapter api
> 
> @MuhweziDeo we should investigate if the tileSize property in the layer object should be configured client or server side

noted

**Comment by MuhweziDeo** [comment]
These are my initial finding on this issue
It seems like when a layer doesn't have a **tileSize** property it defaults to **256**.  So I don't know if there is a way in the client we can target each layer without a **tileSize** property and check if they have a **tileSize** property and set a default of **512**. because the server currently expects the height and width when requesting a layer as seen in this example request  https://dev.nexus.geosolutionsgroup.com/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=geonode:ck_buildings&STYLES=&SRS=EPSG:3857&CRS=EPSG:3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=-18785164.071364917,-3130860.6785608195,-18158991.93565275,-2504688.5428486555. 

The **height** and **width** are got from the tileSize property on the layer object. I have tested as seen that layers returned from GeoServer catalog service don't have tilesize property at least from the `nexus dev instance` i was testing with so hence the default tileSize that will be used in this case is 256

**Comment by allyoucanmap** [comment]
@MuhweziDeo @giohappy 

We should check if the configuration can be provided server side:
- layer injected should have the tileSize equal to 512 in the layer config object (server could do this)
- the csw catalog needs to include the tileSize opttion in the layer, something like (we need to verify if supported by the [MapStore2 submodule](https://github.com/geosolutions-it/MapStore2/tree/geonode-mapstore-client-2.1.x) used by geonode-mapstore-client):

```js
"geonode_csw": {
    "url": "url/to/csw",
    "type": "csw",
    "title": "GeoNode CSW",
    "autoload": true,
    "layerOptions": {
        "tileSize": 512
    }
},
```

- map should keep the saved configuration

only issue that could think right now is about existing map with catalog with old configuration, Maybe the adapter could check the catalogServices option in the map config blob

**Comment by MuhweziDeo** [comment]
currently, the Map store supports enforcing requesting for 512 tiles via the configuration json file by adding `layerOptions.tileSize` to the 512 option hence the catalog service will always make requests basing on the tileSize value provided. So the configurations for the catalog has to be updated with layerOptions.tileSize option expected(**512**) in geonode-client

**Comment by giohappy** [comment]
ok, so the task is server side:

 - add the `layerOptions.tileSize` option to the GeoNode CSW configuration generated by the server
 - add the `tileSize` option to the default layer's configuration inside the map blob

right @allyoucanmap ?

**Comment by giohappy** [comment]
Done in https://github.com/GeoNode/geonode/pull/7624 and https://github.com/GeoNode/geonode-mapstore-client/pull/220
