### ISSUE TITLE
Fullscreen does not work for portals

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#598]
steps to reproduces:

- login
- open a dataset with style edit permissions
- select edit style
- use fullscreen mode
- click on a color picker

expected result

- color picker is visible

current results

- color picker is not visible

**Comment by luorlandini** [comment]
this bug occurs when in fullscreen mode, the user tries to display a component with overlay behavior such as colorpicker, datepicker, modal etc ... if the fullscreen view is appended on a nested div of the "root container", the components with overlay behavior, which are sibling nodes, will not be displayed because they are outside the view port

**Comment by marthamareal** [comment]
The color picker is visible in full-screen mode.
