### ISSUE TITLE
Timing issues with timeline histogram initialization

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#756]
The timeline histogram is not initialized correctly **sometimes**, and the problem seems to be a timing problem (no puns here!) inside the client. It happens more frequently on 3.3.x, but I could reproduce it also on 3.2.x. On master I haven't faced the issue.

Comparing a similar map between 3.3.x and master, I can see that the very first request is always directed to DescribeDomain:

https://master.demo.geonode.org/geoserver/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=geonode:boxes_with_date2&tileMatrixSet=EPSG:4326&expandLimit=10

https://development.demo.geonode.org/geoserver/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=geonode:boxes_with_date&tileMatrixSet=EPSG:4326&expandLimit=10

However, most of the times,  3.2.x/3.3.x client doesn't execute the susequent GetDomainValuea requests that I see on master.

It's very difficult to say why / when it works. On my side the timeline works on 3.3.x if I keep the browser Debug tools closed, but this cannot be reproduced by others. This, and the erratic replication of the problem makes me think it's a timing problem within the client.

MASTER
![image](https://user-images.githubusercontent.com/571129/151386030-83fe724a-d927-4da9-a3ac-5ee850689c41.png)

DEVELOPMENT
![image](https://user-images.githubusercontent.com/571129/151386234-27c95556-b305-4f80-ae5b-e4a6b75b6e23.png)

**Comment by gannebamm** [comment]
Nice! This explains the error I was facing there: https://github.com/GeoNode/geonode/issues/8564

**Comment by allyoucanmap** [comment]
@giohappy the issue was indeed a race condition between the import of the timeline and the initialization of the time dimensions.  If the timeline plugin was taking too long to load the epic streams of actions wasn't ready to get information about the timeline.
Here the fixes where all the epics needed for the timeline has been moved to app initialization to ensure they are available as soon as the map config is loaded:

- master https://github.com/GeoNode/geonode-mapstore-client/pull/763
- 3.3.x https://github.com/GeoNode/geonode-mapstore-client/pull/761
- 3.2.x https://github.com/GeoNode/geonode-mapstore-client/pull/762

I also ported the fix to master even if currently is not reproducible on master probably due to the different load workflow)

**Comment by simboss** [comment]
@giohappy let's ask elena to test this on all branches as soon as this lands.

I want to start manual testing things yesterday rather than waiting any longer.

**Comment by simboss** [comment]
@giohappy we need to fix and test this also for 3.2.x

**Comment by giohappy** [comment]
I know @simboss I 've just created the task for GN 3.2.x
