### ISSUE TITLE
Timeline histogram isn't initialized correctly when switching on a layer that is not visible by default

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#757]
## Description
A map has a layer with time dimensione, which is configured not visible by default.  When the layer is turned on the histogram inside the timeline widget isn't initialized correctly.

## How to reproduce
- Create a new map
- Add a layer with a time dimension
- Turn the layer not visible
- Save the map
- Reopen the map
- Turn the layer on

*Expected Result*
The timline is positioned acording to the histogram data, and the histogram is represented correctly.

*Current Result*
- The histogram is not initialized as expected and the timeline is positioned at the current date

**Comment by giohappy** [comment]
fixed in https://github.com/GeoNode/geonode-mapstore-client/commit/74d9fd6b511cb6fc28736847b250431ca7ab3f44

**Comment by giohappy** [comment]
Apparently it isn't working on 3.2.x yet.

**Comment by allyoucanmap** [comment]
> Apparently it isn't working on 3.2.x yet.

@giohappy The reason is a missing commit in the submodule of 3.2.x that is included in the 3.3.x one:

- https://github.com/geosolutions-it/MapStore2/commit/3c99cd79481ac617034332ee6765988690e178d5

I'm going to update the submodule of 3.2.x backporting this commit and also this one about fix on timeline epics initialization

- https://github.com/allyoucanmap/MapStore2/commit/d36cba2bceab746c2ae265f12df67fa1c311711f

**Comment by allyoucanmap** [comment]
@giohappy PR available here https://github.com/GeoNode/geonode-mapstore-client/pull/775

**Comment by giohappy** [comment]
@allyoucanmap stable demo updated. The issue is gone.
